# Generated by Django 2.2.16 on 2022-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(blank=True, editable=False, max_length=99, null=True, unique=True),
        ),
    ]
